test:debian7:
    image: debian:7
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:debian8:
    image: debian:8
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:debian9:
    image: debian:7
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:ubuntu1404:
    image: ubuntu:14.04
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:ubuntu1604:
    image: ubuntu:16.04
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:ubuntu1704:
    image: ubuntu:17.04
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd    

test:ubuntu1710:
    image: ubuntu:17.10
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:ubuntu1804:
    image: ubuntu:18.04
    script:
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install wget -y
        - apt-get install vnstat -y
        - chmod +x custom_motd
        - ./custom_motd

test:centos7:
    image: centos:latest
    script:
        - yum update -y
        - yum install epel-release -y
        - yum install wget vnstat -y
        - chmod +x custom_motd
        - ./custom_motd


